## Carga de datos

In [ ]:
import pandas as pd

URL='http://fpaniaguapython.github.io/datos/CTA-PCAD-202610%20(respuestas).csv'

df = pd.read_csv(URL)
display(df)

,Marca temporal,Nombre,Sexo,Fecha de nacimiento,Altura,Peso,Patrimonio (en €)
0,20/10/2026 18:11:06,Paco,Hombre,1/02/1995,194,90,55555
1,20/10/2026 18:11:55,Lucia,Mujer,29/10/1996,2 metros,69.5 kg,1000
2,20/10/2026 18:12:07,Miguel Acosta,Hombre,1/02/2001,1.63,62,"2,51"
3,20/10/2026 18:12:19,Deborah Vance,Otros,5/06/1985,170,60,50000
4,20/10/2026 18:12:24,Alex,Hombre,2/08/1985,1.87,NaN,200
5,20/10/2026 18:12:26,Perico,Hombre,6/01/1925,1.74,"74,02","3355,44"
6,20/10/2026 18:12:28,Stitch,Otros,14/01/2005,"1,50m",400kg,628.000
7,20/10/2026 18:12:33,CR7,Otros,12/04/2000,180,80,380000
8,20/10/2026 18:12:35,Carmen,Mujer,8/03/2004,157cm,50 kilos,1000 euros
9,20/10/2026 18:12:36,María Gonzalez,Mujer,15/04/1976,172,63,20000
10,20/10/2026 18:12:41,Pablo,Hombre,4/07/1990,"1,8",70,50000
11,20/10/2026 18:13:05,Juan,Hombre,29/02/1976,4 m,90 kgr,2 mil
12,20/10/2026 18:13:31,Maria Unpajote,Mujer,1/01/2035,158,61,1E+18
13,20/10/2026 18:14:02,Jacques de Lalaing,Hombre,21/07/1421,"168,5 cm",71 kg,"Rentas de los feudos de Lalaing, Hordain, Bugn..."
14,20/10/2026 18:14:10,Felipe,Hombre,13/04/1979,30 cm,75 kg,No lo suficiente.

## Consultar la estructura del df

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Marca temporal       15 non-null     object
 1   Nombre               15 non-null     object
 2   Sexo                 15 non-null     object
 3   Fecha de nacimiento  15 non-null     object
 4   Altura               15 non-null     object
 5   Peso                 14 non-null     object
 6   Patrimonio (en €)    15 non-null     object
dtypes: object(7)
memory usage: 972.0+ bytes

## Consulta de las n primeras filas

In [ ]:
df.head() # Por defecto muestra 5 filas

,Marca temporal,Nombre,Sexo,Fecha de nacimiento,Altura,Peso,Patrimonio (en €)
0,20/10/2026 18:11:06,Paco,Hombre,1/02/1995,194,90,55555
1,20/10/2026 18:11:55,Lucia,Mujer,29/10/1996,2 metros,69.5 kg,1000
2,20/10/2026 18:12:07,Miguel Acosta,Hombre,1/02/2001,1.63,62,"2,51"
3,20/10/2026 18:12:19,Deborah Vance,Otros,5/06/1985,170,60,50000
4,20/10/2026 18:12:24,Alex,Hombre,2/08/1985,1.87,NaN,200

## Consultar las n últimas filas (5 por defecto)

In [ ]:
df.tail()

,Marca temporal,Nombre,Sexo,Fecha de nacimiento,Altura,Peso,Patrimonio (en €)
10,20/10/2026 18:12:41,Pablo,Hombre,4/07/1990,"1,8",70,50000
11,20/10/2026 18:13:05,Juan,Hombre,29/02/1976,4 m,90 kgr,2 mil
12,20/10/2026 18:13:31,Maria Unpajote,Mujer,1/01/2035,158,61,1E+18
13,20/10/2026 18:14:02,Jacques de Lalaing,Hombre,21/07/1421,"168,5 cm",71 kg,"Rentas de los feudos de Lalaing, Hordain, Bugn..."
14,20/10/2026 18:14:10,Felipe,Hombre,13/04/1979,30 cm,75 kg,No lo suficiente.

## Mostrar algunas filas intermedias (al azar)

In [ ]:
# df.sample(5) # 5 filas
df.sample(frac=0.1) # 10%

,Marca temporal,Nombre,Sexo,Fecha de nacimiento,Altura,Peso,Patrimonio (en €)
13,20/10/2026 18:14:02,Jacques de Lalaing,Hombre,21/07/1421,"168,5 cm",71 kg,"Rentas de los feudos de Lalaing, Hordain, Bugn..."
14,20/10/2026 18:14:10,Felipe,Hombre,13/04/1979,30 cm,75 kg,No lo suficiente.

## Seleccionar la columna Nombre

In [ ]:
nombres = df['Nombre'] # Acceso a la columna Nombre
type(nombres) # El tipo es Series

pandas.core.series.Series

In [ ]:
# df_copia = df # Ambas variables apuntan al mismo dataframe
df_copia = df.copy(deep=True) # deep=True por defecto, no es necesario
df_copia['Nombre']='Desconocido'
display(df.head())
display(df_copia.head())

,Marca temporal,Nombre,Sexo,Fecha de nacimiento,Altura,Peso,Patrimonio (en €)
0,20/10/2026 18:11:06,Paco,Hombre,1/02/1995,194,90,55555
1,20/10/2026 18:11:55,Lucia,Mujer,29/10/1996,2 metros,69.5 kg,1000
2,20/10/2026 18:12:07,Miguel Acosta,Hombre,1/02/2001,1.63,62,"2,51"
3,20/10/2026 18:12:19,Deborah Vance,Otros,5/06/1985,170,60,50000
4,20/10/2026 18:12:24,Alex,Hombre,2/08/1985,1.87,NaN,200

,Marca temporal,Nombre,Sexo,Fecha de nacimiento,Altura,Peso,Patrimonio (en €)
0,20/10/2026 18:11:06,Desconocido,Hombre,1/02/1995,194,90,55555
1,20/10/2026 18:11:55,Desconocido,Mujer,29/10/1996,2 metros,69.5 kg,1000
2,20/10/2026 18:12:07,Desconocido,Hombre,1/02/2001,1.63,62,"2,51"
3,20/10/2026 18:12:19,Desconocido,Otros,5/06/1985,170,60,50000
4,20/10/2026 18:12:24,Desconocido,Hombre,2/08/1985,1.87,NaN,200