## Conversión de wide a long utilizando la función pd.melt

In [ ]:
import pandas as pd

wide_data = {
    'year': [2023, 2024, 2025],
    'Alice': [50000, 60000, 70000],
    'Bob': [55000, 65000, 75000],
    'Charlie': [60000, 70000, 80000],
    'David': [65000, 75000, 85000]
}

wide_df = pd.DataFrame(wide_data)

display(wide_df)

   year  Alice    Bob  Charlie  David
0  2023  50000  55000    60000  65000
1  2024  60000  65000    70000  75000
2  2025  70000  75000    80000  85000

## Conversión en formato long utilizando pd.melt

In [ ]:
long_df = pd.melt(
    frame=wide_df,
    id_vars = 'year',
    var_name = 'employee',
    value_name = 'salary')

display(long_df)

    year employee  salary
0   2023    Alice   50000
1   2024    Alice   60000
2   2025    Alice   70000
3   2023      Bob   55000
4   2024      Bob   65000
5   2025      Bob   75000
6   2023  Charlie   60000
7   2024  Charlie   70000
8   2025  Charlie   80000
9   2023    David   65000
10  2024    David   75000
11  2025    David   85000

## Salarios de Alice

In [ ]:
long_df.loc[long_df['employee'] == 'Alice', 'salary']

0    50000
1    60000
2    70000
Name: salary, dtype: int64

## Medias por empleado

In [ ]:
df_media = long_df.groupby("employee")["salary"].mean()
df_media

employee
Alice      60000.0
Bob        65000.0
Charlie    70000.0
David      75000.0
Name: salary, dtype: float64