In [47]:
import pandas as pd

## Crear un fichero (principios.txt) con la lista de principios activos siguiente y almacenarla en la zona de almacenamiento de Colab

* Paracetamol
* Ibuprofeno
* Ácido acetilsalicílico
* Omeprazol
* Amoxicilina
* Loratadina
* Cetirizina
* Metformina
* Loperamida
* Diclofenaco

In [48]:
principios_activos = [
    "Paracetamol",
    "Ibuprofeno",
    "Ácido acetilsalicílico",
    "Omeprazol",
    "Amoxicilina",
    "Loratadina",
    "Cetirizina",
    "Metformina",
    "Loperamida",
    "Diclofenaco"
]
with open('principios.txt', mode='wt', encoding='utf-8') as fichero_principios:
  for principio_activo in principios_activos:
    fichero_principios.write(f"{principio_activo}\n")

## Función de validación de días de la semana

In [49]:
def validar_dia_semana(dia_a_verificar: str) -> bool:
    DIAS_SEMANA = ['LUNES', 'MARTES', 'MIÉRCOLES', 'JUEVES', 'VIERNES']
    es_valido = dia_a_verificar in DIAS_SEMANA
    return es_valido

## Función de validación de los principios activos

In [50]:
principios_activos = None

def leer_principios_activos(nombre_fichero: str) -> list:
    with open(nombre_fichero, mode='rt', encoding='utf-8') as fichero:
        principios_activos = fichero.readlines()
    principios_activos = [principio_activo.strip() for principio_activo in principios_activos]
    return principios_activos

if principios_activos is None:
  principios_activos = leer_principios_activos('principios.txt')

def validar_principios_activos(principios_activos: list, principio_activo: str) -> bool:
    principio_valido = principio_activo in principios_activos
    return principio_valido

## Dataset

In [51]:
pedido = {
    "id_pedido": [1, 2, 3, 4, 5, 6],
    "dia_entrega": ["LUNES", "MARTES", "MIÉRCOLES", "MARTES", "JUEVES", "SÁBADO"],
    "id_cliente": [101, 102, 103, 104, 105, 106],
    "principio_activo": ["Loperamida", "Diclofenaco", "Ibuprofeno", "Paracetamol", "Gaseosa", "Metformina"]
}
df = pd.DataFrame(pedido)
display(df)

   id_pedido dia_entrega  id_cliente principio_activo
0          1       LUNES         101       Loperamida
1          2      MARTES         102      Diclofenaco
2          3   MIÉRCOLES         103       Ibuprofeno
3          4      MARTES         104      Paracetamol
4          5      JUEVES         105          Gaseosa
5          6      SÁBADO         106       Metformina

## Comprobar que todos los días de las semana son válidos

In [52]:
dias_semana_correctos = df['dia_entrega'].apply(validar_dia_semana).all()
display(dias_semana_correctos)

np.False_

## Comprobar que todos los principios activos son válidos

In [53]:
principios_correctos = df['principio_activo'].apply(
    lambda principio : validar_principios_activos(principios_activos, principio)).all()
display(principios_correctos)

np.False_

## Obtener los valores válidos de días de las semana

> Añadir blockquote

In [54]:
df_dias_validos = df[df['dia_entrega'].apply(validar_dia_semana)]
display(df_dias_validos)

   id_pedido dia_entrega  id_cliente principio_activo
0          1       LUNES         101       Loperamida
1          2      MARTES         102      Diclofenaco
2          3   MIÉRCOLES         103       Ibuprofeno
3          4      MARTES         104      Paracetamol
4          5      JUEVES         105          Gaseosa

## Obtener los valores NO válidos de días de las semana

In [55]:
df_dias_validos = df[~df['dia_entrega'].apply(validar_dia_semana)]
display(df_dias_validos)

   id_pedido dia_entrega  id_cliente principio_activo
5          6      SÁBADO         106       Metformina

## Obtención de los elementos cuyos principios activos son correctos

In [57]:
df_principios_validos = df[df['principio_activo'].apply(
    lambda principio : validar_principios_activos(principios_activos, principio)
)]
display(df_principios_validos)

   id_pedido dia_entrega  id_cliente principio_activo
0          1       LUNES         101       Loperamida
1          2      MARTES         102      Diclofenaco
2          3   MIÉRCOLES         103       Ibuprofeno
3          4      MARTES         104      Paracetamol
5          6      SÁBADO         106       Metformina

## Obtención de los elementos cuyos principios activos NO son correctos

In [58]:
df_principios_no_validos = df[~df['principio_activo'].apply(
    lambda principio : validar_principios_activos(principios_activos, principio)
)]
display(df_principios_no_validos)

   id_pedido dia_entrega  id_cliente principio_activo
4          5      JUEVES         105          Gaseosa